[tool.poetry]
name = "{{ cookiecutter.repo_name }}"
version = "0.1.0"
description = "{{ cookiecutter.description }}"
authors = ["{{ cookiecutter.author_name }}"]
license = "{{ cookiecutter.open_source_license }}"

[tool.poetry.dependencies]
python = "^3.6"
python-dotenv = "^0.10.3"
joblib = "^0.13"

[tool.poetry.dev-dependencies]
black = "^19.3b0"
coverage = "^4.5"
flake8 = "^3.7"
ipykernel = "^5.1"
ipython = "^7.6"
pytest = "^5.0"

mock = "^3.0"
sphinx = "^2.1"
sphinx_rtd_theme = "^0.4"
recommonmark = "^0.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 120
target_version = ['py36']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.idea
  | _build
  | buck-out
  | build
  | dist
  | doc
)/
'''
